version: '3.2'
services:
  local-dbaas-mariadb-provider:
    build:
      context: test-resources
      dockerfile: Dockerfile.mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '33066:3306'
  local-dbaas-provider-mariadb-multi:
    build:
      context: test-resources
      dockerfile: Dockerfile.mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '33067:3306'
  mysql:
    image: amazeeio/alpine-mysql-client
    environment:
      MYSQL_PWD: 'password'
    stdin_open: true
  local-dbaas-psql-provider:
    build:
      context: test-resources
      dockerfile: Dockerfile.postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres'
    ports:
      - '5432:5432'
