{{- range $providerName, $providerConfig := .Values.providers }}
---
apiVersion: mariadb.amazee.io/v1
kind: MariaDBProvider
metadata:
  name: {{ $providerName }}
spec:
  environment: {{ $providerConfig.environment | quote }}
  hostname:  {{ $providerConfig.hostname | quote }}
  readReplicaHostnames:
    {{- toYaml $providerConfig.readReplicaHostnames | nindent 4 }}
  passwordSecretRef:
    name: {{ $providerConfig.passwordSecretRef.name | quote }}
    key: {{ $providerConfig.passwordSecretRef.key | quote }}
  {{- else if $providerConfig.password }}  
  password: {{ $providerConfig.password | quote }}
  {{- end }}
  port: {{ $providerConfig.port | quote }}
  user: {{ $providerConfig.user | quote }}
  type: {{ $providerConfig.type | quote | default "generic" }}
{{- end }}