# Test: This resource intentionally uses the `password` field directly
# and does NOT provide `passwordSecretRef`, to ensure the controller
# correctly uses the plain string password when a secret is not configured.
apiVersion: mariadb.amazee.io/v1
kind: MariaDBProvider
metadata:
  name: mariadbprovider-testing-multi1
spec:
  environment: multi
  hostname: multi1.mariadb.172.17.0.1.nip.io
  readReplicaHostnames:
  - multi1.mariadb.172.17.0.1.nip.io
  passwordSecretRef:
    name: mariadb-secret
    key: password
  port: '33066'
  user: root
---
apiVersion: mariadb.amazee.io/v1
kind: MariaDBProvider
metadata:
  name: mariadbprovider-testing-multi2
spec:
  environment: multi
  hostname: multi2.mariadb.172.17.0.1.nip.io
  readReplicaHostnames:
  - multi2.mariadb.172.17.0.1.nip.io
  passwordSecretRef:
    name: mariadb-secret
    key: password
  port: '33067'
  user: root

---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  password: cGFzc3dvcmQ=  # base64 encoded string of "password"
