apiVersion: mariadb.amazee.io/v1
kind: MariaDBProvider
metadata:
  name: mariadbprovider-testing
spec:
  environment: test
  hostname: mariadb.172.17.0.1.nip.io
  readReplicaHostnames:
  - mariadb.172.17.0.1.nip.io
  passwordSecretRef:
    name: my-db-secret
    key: password
  port: '33066'
  user: root

---
apiVersion: v1
kind: Secret
metadata:
  name: my-db-secret
  namespace: default
type: Opaque
data:
  password: cGFzc3dvcmQ= # base64-encoded value of "password"