# permissions to do edit mariadbconsumers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadbconsumer-editor-role
rules:
- apiGroups:
  - mariadb.amazee.io
  resources:
  - mariadbconsumers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.amazee.io
  resources:
  - mariadbconsumers/status
  verbs:
  - get
  - patch
  - update
