# permissions to do viewer mariadbconsumers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadbconsumer-viewer-role
rules:
- apiGroups:
  - mariadb.amazee.io
  resources:
  - mariadbconsumers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mariadb.amazee.io
  resources:
  - mariadbconsumers/status
  verbs:
  - get
