# permissions to do edit mariadbproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadbprovider-editor-role
rules:
- apiGroups:
  - mariadb.amazee.io
  resources:
  - mariadbproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.amazee.io
  resources:
  - mariadbproviders/status
  verbs:
  - get
  - patch
  - update
