# permissions to do viewer mariadbproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadbprovider-viewer-role
rules:
- apiGroups:
  - mariadb.amazee.io
  resources:
  - mariadbproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mariadb.amazee.io
  resources:
  - mariadbproviders/status
  verbs:
  - get
