# permissions to do viewer postgresqlproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqlprovider-viewer-role
rules:
- apiGroups:
  - postgres.amazee.io
  resources:
  - postgresqlproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgres.amazee.io
  resources:
  - postgresqlproviders/status
  verbs:
  - get
