# permissions to do edit postgresqlconsumers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqlconsumer-editor-role
rules:
- apiGroups:
  - postgres.amazee.io
  resources:
  - postgresqlconsumers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.amazee.io
  resources:
  - postgresqlconsumers/status
  verbs:
  - get
  - patch
  - update
