# permissions to do edit postgresqlproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqlprovider-editor-role
rules:
- apiGroups:
  - postgres.amazee.io
  resources:
  - postgresqlproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.amazee.io
  resources:
  - postgresqlproviders/status
  verbs:
  - get
  - patch
  - update
