apiVersion: v1
entries:
  dbaas-operator:
  - apiVersion: v2
    appVersion: v0.3.0
    created: "2025-01-08T08:55:55.495513993+11:00"
    description: A Helm chart for dbaas-operator
    digest: 1a00343547c5308044a8b47d72f019c02217d3468e11ff64bd75933efb980ba3
    kubeVersion: '>= 1.19.0-0'
    name: dbaas-operator
    type: application
    urls:
    - dbaas-operator-0.3.2.tgz
    version: 0.3.2
  - apiVersion: v2
    appVersion: v0.3.0
    created: "2025-01-08T08:55:55.49529833+11:00"
    description: A Helm chart for dbaas-operator
    digest: d4528ea328d76d93f9a1d2d610e6a370ec98f235745ba4a4c8d24ea2c9b99ae1
    kubeVersion: '>= 1.19.0-0'
    name: dbaas-operator
    type: application
    urls:
    - dbaas-operator-0.3.1.tgz
    version: 0.3.1
  - apiVersion: v2
    appVersion: v0.3.0
    created: "2025-01-08T08:55:55.495081509+11:00"
    description: A Helm chart for dbaas-operator
    digest: cc0522c57358a26efb03b6ad3da4bfe51b94c87c8cb89f998e120032139fe7fb
    kubeVersion: '>= 1.19.0-0'
    name: dbaas-operator
    type: application
    urls:
    - dbaas-operator-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: v0.2.2
    created: "2025-01-08T08:55:55.494865964+11:00"
    description: A Helm chart for dbaas-operator
    digest: a02889fc2fc60574ebe2994af8b664dd4805b67ad240315fcaebff2688a55f60
    name: dbaas-operator
    type: application
    urls:
    - dbaas-operator-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: v0.2.1
    created: "2025-01-08T08:55:55.494652974+11:00"
    description: A Helm chart for dbaas-operator
    digest: 45e600f560d6200b4ac5e594b776d620f2285c3e611db8661f981e42755cd736
    name: dbaas-operator
    type: application
    urls:
    - dbaas-operator-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 0.1.6
    created: "2025-01-08T08:55:55.493127824+11:00"
    description: A Helm chart for dbaas-operator
    digest: f492d4b57e93bc669d23a5fe1f463db509d190abf3c54b856b53bfa89dc7f102
    name: dbaas-operator
    type: application
    urls:
    - dbaas-operator-0.1.10.tgz
    version: 0.1.10
  - apiVersion: v2
    appVersion: 0.1.6
    created: "2025-01-08T08:55:55.494437581+11:00"
    description: A Helm chart for dbaas-operator
    digest: adcdb786874274e0754330587b11bae63216656259fb0569188a553002c1c3e3
    name: dbaas-operator
    type: application
    urls:
    - dbaas-operator-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: 0.1.5rc3
    created: "2025-01-08T08:55:55.494242634+11:00"
    description: A Helm chart for dbaas-operator
    digest: c9a5323d4923bb3b9f2188773cbb7ce0badc0de0166da73487064b35154ea72c
    name: dbaas-operator
    type: application
    urls:
    - dbaas-operator-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    appVersion: 0.1.3
    created: "2025-01-08T08:55:55.494046617+11:00"
    description: A Helm chart for dbaas-operator
    digest: a3e809db9edeef3d3b5708cb45a58b8318c2864d5ffab684a4e239ed5e8dd118
    name: dbaas-operator
    type: application
    urls:
    - dbaas-operator-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 0.1.2
    created: "2025-01-08T08:55:55.493857878+11:00"
    description: A Helm chart for dbaas-operator
    digest: da29683319a4964eccf17ef2aa45caeffda9100acdf22f76869185c7174be65c
    name: dbaas-operator
    type: application
    urls:
    - dbaas-operator-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2025-01-08T08:55:55.493660772+11:00"
    description: A Helm chart for dbaas-operator
    digest: c3f995573c09f887b0fd4370fb07b4148eb1d61f5f5ce3baddf01dd953c724cf
    name: dbaas-operator
    type: application
    urls:
    - dbaas-operator-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-01-08T08:55:55.493489625+11:00"
    description: A Helm chart for dbaas-operator
    digest: 67712098bd65fce262f59cfcb5566bcd9dee5c0f75afbeccb78bf4776a0b657d
    name: dbaas-operator
    type: application
    urls:
    - dbaas-operator-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-01-08T08:55:55.493310154+11:00"
    description: A Helm chart for dbaas-operator
    digest: 16294c3b156e3d6192f9205358bce552952c75b8d28b06d37fbc4804e960cd8d
    name: dbaas-operator
    type: application
    urls:
    - dbaas-operator-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-01-08T08:55:55.492901971+11:00"
    description: A Helm chart for dbaas-operator
    digest: f0f32afe174f62ea1ba792d6a564223cd0ed6ac821bdf7a09cf5c254f02f2fac
    name: dbaas-operator
    type: application
    urls:
    - dbaas-operator-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-01-08T08:55:55.492729656+11:00"
    description: A Helm chart for dbaas-operator
    digest: 49e3bac9fd6a6eea448accd9483d9fbacd3a3b0b3e2e146c7304b558438c0df2
    name: dbaas-operator
    type: application
    urls:
    - dbaas-operator-0.1.0.tgz
    version: 0.1.0
  mariadbprovider:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-01-08T08:55:55.495729381+11:00"
    description: A Helm chart for MariaDBProvider used by dbaas-operator
    digest: b555d1e80be0d034091740cecf41f99bf5ff297ba4f21772b1160be83afb5751
    name: mariadbprovider
    type: application
    urls:
    - mariadbprovider-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-01-08T08:55:55.49565763+11:00"
    description: A Helm chart for MariaDBProvider used by dbaas-operator
    digest: a59bd057c64ca68b2f52a8b1a6dece0746ebc0ee0f1a6a17c807c8df5d6a0c3e
    name: mariadbprovider
    type: application
    urls:
    - mariadbprovider-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-01-08T08:55:55.495584537+11:00"
    description: A Helm chart for MariaDBProvider used by dbaas-operator
    digest: bc03d2aa3c0d0aba80063294dbf467cb79b32a408cb34dec1841b531ebd2094c
    name: mariadbprovider
    type: application
    urls:
    - mariadbprovider-0.1.1.tgz
    version: 0.1.1
  mongodbprovider:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-01-08T08:55:55.495973711+11:00"
    description: A Helm chart for MongoDBProvider used by dbaas-operator
    digest: b95f3991e86f665f5a4b7a1a61c67eeecb34258b2a28b35298010b7ec22d84b2
    name: mongodbprovider
    type: application
    urls:
    - mongodbprovider-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-01-08T08:55:55.495891188+11:00"
    description: A Helm chart for MongoDBProvider used by dbaas-operator
    digest: 0cd16ed15beda252eeea69a6c2254f926bb200648321c7d7bd514f2b4f7655ef
    name: mongodbprovider
    type: application
    urls:
    - mongodbprovider-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-01-08T08:55:55.49580822+11:00"
    description: A Helm chart for MongoDBProvider used by dbaas-operator
    digest: fda5cbc7411eeeb58af9e730aad5bca83a3a22ebc2100a4d71ca5165eef3d6fb
    name: mongodbprovider
    type: application
    urls:
    - mongodbprovider-0.1.0.tgz
    version: 0.1.0
  postgresqlprovider:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-01-08T08:55:55.496139959+11:00"
    description: A Helm chart for PostgreSQLProvider used by dbaas-operator
    digest: d7fc208bfad22900ddeee2fc9a92292361ae6ac5a52da7b2822762243a658e60
    name: postgresqlprovider
    type: application
    urls:
    - postgresqlprovider-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-01-08T08:55:55.496052213+11:00"
    description: A Helm chart for PostgreSQLProvider used by dbaas-operator
    digest: 27b6b05d4dfa94020fe122afa69cfe2c4bba351b8b069a660a0403de262ba567
    name: postgresqlprovider
    type: application
    urls:
    - postgresqlprovider-0.1.0.tgz
    version: 0.1.0
generated: "2025-01-08T08:55:55.492457095+11:00"
