apiVersion: v1
entries:
  dbaas-operator:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-02-09T18:36:35.38512-06:00"
    description: A Helm chart for dbaas-operator
    digest: 49e3bac9fd6a6eea448accd9483d9fbacd3a3b0b3e2e146c7304b558438c0df2
    name: dbaas-operator
    type: application
    urls:
    - dbaas-operator-0.1.0.tgz
    version: 0.1.0
  mariadbprovider:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-02-09T18:36:35.385364-06:00"
    description: A Helm chart for MariaDBProvider used by dbaas-operator
    digest: bc03d2aa3c0d0aba80063294dbf467cb79b32a408cb34dec1841b531ebd2094c
    name: mariadbprovider
    type: application
    urls:
    - mariadbprovider-0.1.1.tgz
    version: 0.1.1
generated: "2020-02-09T18:36:35.384027-06:00"
