{{- range $providerName, $providerConfig := .Values.providers }}
---
apiVersion: mongodb.amazee.io/v1
kind: MongoDBProvider
metadata:
  name: {{ $providerName }}
spec:
  environment: {{ $providerConfig.environment | quote }}
  hostname:  {{ $providerConfig.hostname | quote }}
  passwordSecretRef:
    name: {{ $providerConfig.passwordSecretRef.name | quote }}
    key: {{ $providerConfig.passwordSecretRef.key | quote }}
  {{- else if $providerConfig.password }}
  password: {{ $providerConfig.password | quote }}
  {{- end }}
  port: {{ $providerConfig.port | quote }}
  user: {{ $providerConfig.user | quote }}
  type: {{ $providerConfig.type | quote | default "generic" }}
  auth:
    mechanism: {{ $providerConfig.auth.mechanism | quote }}
    source: {{ $providerConfig.auth.source | quote }}
    tls: {{ $providerConfig.auth.tls | default false }}
{{- end }}