---
apiVersion: mariadb.amazee.io/v1
kind: MariaDBProvider
metadata:
  name: mariadbprovider-development
spec:
  environment: development
  hostname: 172.17.0.1
  readReplicaHostnames: 
  - 172.17.0.1
  password: password
  port: '3396'
  user: root
 
---
kind: MariaDBProvider
metadata:
  name: mariadbprovider-production
spec:
  environment: production
  hostname: 172.17.0.1
  readReplicaHostnames: 
  - 172.17.0.1
  password: password
  port: '3396'
  user: root

# ---
# apiVersion: mariadb.amazee.io/v1
# kind: MariaDBProvider
# metadata:
#   name: mariadbprovider-azure-production-1
# spec:
#   environment: production
#   hostname: mymariadb.mariadb.database.azure.com
#   readReplicaHostnames: 
#   - mymariadb.mariadb.database.azure.com
#   password: myPassword
#   port: '3306'
#   type: azure # required for azure
#   user: root@mymariadb # azure expects to be connected via "user@host"
