//go:build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLConsumer) DeepCopyInto(out *PostgreSQLConsumer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLConsumer.
func (in *PostgreSQLConsumer) DeepCopy() *PostgreSQLConsumer {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLConsumer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgreSQLConsumer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLConsumerData) DeepCopyInto(out *PostgreSQLConsumerData) {
	*out = *in
	out.Services = in.Services
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLConsumerData.
func (in *PostgreSQLConsumerData) DeepCopy() *PostgreSQLConsumerData {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLConsumerData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLConsumerList) DeepCopyInto(out *PostgreSQLConsumerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PostgreSQLConsumer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLConsumerList.
func (in *PostgreSQLConsumerList) DeepCopy() *PostgreSQLConsumerList {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLConsumerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgreSQLConsumerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLConsumerProvider) DeepCopyInto(out *PostgreSQLConsumerProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLConsumerProvider.
func (in *PostgreSQLConsumerProvider) DeepCopy() *PostgreSQLConsumerProvider {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLConsumerProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLConsumerServices) DeepCopyInto(out *PostgreSQLConsumerServices) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLConsumerServices.
func (in *PostgreSQLConsumerServices) DeepCopy() *PostgreSQLConsumerServices {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLConsumerServices)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLConsumerSpec) DeepCopyInto(out *PostgreSQLConsumerSpec) {
	*out = *in
	out.Provider = in.Provider
	out.Consumer = in.Consumer
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLConsumerSpec.
func (in *PostgreSQLConsumerSpec) DeepCopy() *PostgreSQLConsumerSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLConsumerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLConsumerStatus) DeepCopyInto(out *PostgreSQLConsumerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLConsumerStatus.
func (in *PostgreSQLConsumerStatus) DeepCopy() *PostgreSQLConsumerStatus {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLConsumerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLProvider) DeepCopyInto(out *PostgreSQLProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLProvider.
func (in *PostgreSQLProvider) DeepCopy() *PostgreSQLProvider {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgreSQLProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLProviderList) DeepCopyInto(out *PostgreSQLProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PostgreSQLProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLProviderList.
func (in *PostgreSQLProviderList) DeepCopy() *PostgreSQLProviderList {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgreSQLProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLProviderSpec) DeepCopyInto(out *PostgreSQLProviderSpec) {
	*out = *in
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLProviderSpec.
func (in *PostgreSQLProviderSpec) DeepCopy() *PostgreSQLProviderSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLProviderStatus) DeepCopyInto(out *PostgreSQLProviderStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLProviderStatus.
func (in *PostgreSQLProviderStatus) DeepCopy() *PostgreSQLProviderStatus {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}
