apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dbaas-operator.fullname" . }}-manager
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.amazee.io
  resources:
  - mariadbconsumers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.amazee.io
  resources:
  - mariadbconsumers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mariadb.amazee.io
  resources:
  - mariadbproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.amazee.io
  resources:
  - mariadbproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - postgres.amazee.io
  resources:
  - postgresqlconsumers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.amazee.io
  resources:
  - postgresqlconsumers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - postgres.amazee.io
  resources:
  - postgresqlproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.amazee.io
  resources:
  - postgresqlproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mongodb.amazee.io
  resources:
  - mongodbconsumers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mongodb.amazee.io
  resources:
  - mongodbconsumers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mongodb.amazee.io
  resources:
  - mongodbproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mongodb.amazee.io
  resources:
  - mongodbproviders/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dbaas-operator.fullname" . }}-proxy
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
{{if .Values.enableMariaDBProviders}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dbaas-operator.fullname" . }}-mariadbconsumer-role
  labels:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["mariadb.amazee.io"]
  resources: ["mariadbconsumers"]
  verbs: ["*"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dbaas-operator.fullname" . }}-mariadbprovider-role
  labels:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["mariadb.amazee.io"]
  resources: ["mariadbproviders"]
  verbs: ["*"]
{{- end }}
{{if .Values.enablePostreSQLProviders}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dbaas-operator.fullname" . }}-postgresqlconsumer-role
  labels:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["postgres.amazee.io"]
  resources: ["postgresqlconsumers"]
  verbs: ["*"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dbaas-operator.fullname" . }}-postgresqlprovider-role
  labels:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["postgres.amazee.io"]
  resources: ["postgresqlproviders"]
  verbs: ["*"]
{{- end }}
{{if .Values.enableMongoDBProviders}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dbaas-operator.fullname" . }}-mongodbconsumer-role
  labels:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["mongodb.amazee.io"]
  resources: ["mongodbconsumers"]
  verbs: ["*"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dbaas-operator.fullname" . }}-mongodbprovider-role
  labels:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["mongodb.amazee.io"]
  resources: ["mongodbproviders"]
  verbs: ["*"]
{{- end }}
