apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dbaas-operator.fullname" . }}
  labels:
    {{- include "dbaas-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dbaas-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dbaas-operator.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "dbaas-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - args:
          - --secure-listen-address=0.0.0.0:8443
          - --upstream=http://127.0.0.1:8080/
          - --logtostderr=true
          - --v=10
          image: "{{ .Values.kubeRbacProxy.image.repository }}:{{ .Values.kubeRbacProxy.image.tag }}"
          name: kube-rbac-proxy
          ports:
          - containerPort: 8443
            name: https
        - args:
          - --metrics-addr=127.0.0.1:8080
          - --enable-leader-election
          {{- if .Values.enableMariaDBProviders }}
          - --enable-mariadb-providers
          {{- end }}
          {{- if .Values.enableMongoDBProviders }}
          - --enable-mongodb-providers
          {{- end }}
          {{- if .Values.enablePostreSQLProviders }}
          - --enable-postgresql-providers
          {{- end }}
          command:
          - /manager
          image: "{{ .Values.image.repository }}:{{ coalesce .Values.image.tag .Chart.AppVersion }}"
          name: manager
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 20Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
