providers:

  # production:
  #   environment: production
  #   hostname: 172.17.0.1.nip.io
  #   password: password
  #   port: '3306'
  #   user: root

  # development:
  #   environment: development
  #   hostname: 172.17.0.1.nip.io
  #   password: password
  #   port: '3306'
  #   user: root