// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBConsumer) DeepCopyInto(out *MariaDBConsumer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBConsumer.
func (in *MariaDBConsumer) DeepCopy() *MariaDBConsumer {
	if in == nil {
		return nil
	}
	out := new(MariaDBConsumer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MariaDBConsumer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBConsumerData) DeepCopyInto(out *MariaDBConsumerData) {
	*out = *in
	in.Services.DeepCopyInto(&out.Services)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBConsumerData.
func (in *MariaDBConsumerData) DeepCopy() *MariaDBConsumerData {
	if in == nil {
		return nil
	}
	out := new(MariaDBConsumerData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBConsumerList) DeepCopyInto(out *MariaDBConsumerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MariaDBConsumer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBConsumerList.
func (in *MariaDBConsumerList) DeepCopy() *MariaDBConsumerList {
	if in == nil {
		return nil
	}
	out := new(MariaDBConsumerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MariaDBConsumerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBConsumerProvider) DeepCopyInto(out *MariaDBConsumerProvider) {
	*out = *in
	if in.ReadReplicaHostnames != nil {
		in, out := &in.ReadReplicaHostnames, &out.ReadReplicaHostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBConsumerProvider.
func (in *MariaDBConsumerProvider) DeepCopy() *MariaDBConsumerProvider {
	if in == nil {
		return nil
	}
	out := new(MariaDBConsumerProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBConsumerServices) DeepCopyInto(out *MariaDBConsumerServices) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBConsumerServices.
func (in *MariaDBConsumerServices) DeepCopy() *MariaDBConsumerServices {
	if in == nil {
		return nil
	}
	out := new(MariaDBConsumerServices)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBConsumerSpec) DeepCopyInto(out *MariaDBConsumerSpec) {
	*out = *in
	in.Provider.DeepCopyInto(&out.Provider)
	in.Consumer.DeepCopyInto(&out.Consumer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBConsumerSpec.
func (in *MariaDBConsumerSpec) DeepCopy() *MariaDBConsumerSpec {
	if in == nil {
		return nil
	}
	out := new(MariaDBConsumerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBConsumerStatus) DeepCopyInto(out *MariaDBConsumerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBConsumerStatus.
func (in *MariaDBConsumerStatus) DeepCopy() *MariaDBConsumerStatus {
	if in == nil {
		return nil
	}
	out := new(MariaDBConsumerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBProvider) DeepCopyInto(out *MariaDBProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBProvider.
func (in *MariaDBProvider) DeepCopy() *MariaDBProvider {
	if in == nil {
		return nil
	}
	out := new(MariaDBProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MariaDBProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBProviderList) DeepCopyInto(out *MariaDBProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MariaDBProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBProviderList.
func (in *MariaDBProviderList) DeepCopy() *MariaDBProviderList {
	if in == nil {
		return nil
	}
	out := new(MariaDBProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MariaDBProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBProviderSpec) DeepCopyInto(out *MariaDBProviderSpec) {
	*out = *in
	if in.ReadReplicaHostnames != nil {
		in, out := &in.ReadReplicaHostnames, &out.ReadReplicaHostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBProviderSpec.
func (in *MariaDBProviderSpec) DeepCopy() *MariaDBProviderSpec {
	if in == nil {
		return nil
	}
	out := new(MariaDBProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBProviderStatus) DeepCopyInto(out *MariaDBProviderStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBProviderStatus.
func (in *MariaDBProviderStatus) DeepCopy() *MariaDBProviderStatus {
	if in == nil {
		return nil
	}
	out := new(MariaDBProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}
