apiVersion: mongodb.amazee.io/v1
kind: MongoDBProvider
metadata:
  name: mongodbprovider-tls-testing
spec:
  environment: tls-test
  hostname: mongodb.172.17.0.1.nip.io
  password: password
  port: '27018'
  user: root
  auth:
    mechanism: SCRAM-SHA-1
    source: admin
    tls: true