apiVersion: mariadb.amazee.io/v1
kind: MariaDBConsumer
metadata:
  name: mariadbconsumer-testing-2
spec:
  environment: test
  consumer:
    database: testdb
    password: testdb
    username: testdb
  provider:
    hostname: 172.17.0.1.xip.io
    name: mariadbprovider-testing
    namespace: default
    port: "33066"
    readReplicas:
    - 172.17.0.1.xip.io