apiVersion: mariadb.amazee.io/v1
kind: MariaDBConsumer
metadata:
  name: mariadbconsumer-testing-3
spec:
  environment: test
  consumer:
    database: testdb1
    password: testdb1
    username: testdb1
  provider:
    hostname: mariadb.172.17.0.1.nip.io
    port: "33066"
    readReplicas:
    - mariadb.172.17.0.1.nip.io