apiVersion: mariadb.amazee.io/v1
kind: MariaDBProvider
metadata:
  name: mariadbprovider-testing-azure
spec:
  environment: azure
  type: azure
  hostname: azure.mariadb.172.17.0.1.nip.io
  readReplicaHostnames:
  - azure.mariadb.172.17.0.1.nip.io
  password: password
  port: '33066'
  user: root
---
apiVersion: mariadb.amazee.io/v1
kind: MariaDBProvider
metadata:
  name: mariadbprovider-testing-azure-longhost
spec:
  environment: azure-long
  type: azure
  hostname: a.very.very.long.hostname.for.azure.mariadb.172.17.0.1.nip.io
  readReplicaHostnames:
  - a.very.very.long.hostname.for.azure.mariadb.172.17.0.1.nip.io
  password: password
  port: '33066'
  user: root
