apiVersion: mariadb.amazee.io/v1
kind: MariaDBProvider
metadata:
  name: mariadbprovider-testing-azure
spec:
  environment: azure
  type: azure
  hostname: 172.17.0.1.nip.io
  readReplicaHostnames:
  - 172.17.0.1.nip.io
  password: password
  port: '33066'
  user: root