name: DBaaS Operator Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-suite:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        kindest_node_version: [v1.29.14@sha256:8703bd94ee24e51b778d5556ae310c6c0fa67d761fae6379c8e0bb480e6fea29]
        experimental: [false]
        include:
          - kindest_node_version: v1.30.10@sha256:4de75d0e82481ea846c0ed1de86328d821c1e6a6a91ac37bf804e5313670e507
            experimental: false
          - kindest_node_version: v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f
            experimental: false
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: "0"
    - name: Setup correct Go version
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'
    - name: Install kustomize, kubebuilder, helm
      run: |
        #kustomize
        curl -sLo /tmp/kustomize_v3.5.4_linux_amd64.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.5.4/kustomize_v3.5.4_linux_amd64.tar.gz
        sudo tar -C /usr/local/bin -xzf /tmp/kustomize_v3.5.4_linux_amd64.tar.gz
        #kubebuilder
        curl -sL https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.2/kubebuilder_2.3.2_linux_amd64.tar.gz | tar -xz -C /tmp/
        sudo mv /tmp/kubebuilder_2.3.2_linux_amd64 /usr/local/kubebuilder
        echo "/usr/local/kubebuilder/bin" >> $GITHUB_PATH
        #helm
        curl -sL https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz | tar -xz -C /tmp/
        sudo mv /tmp/linux-amd64/helm /usr/local/bin/helm
        chmod +x /usr/local/bin/helm
    - name: Check go, kustomize, kubebuilder, helm, docker compose, kind versions
      run: |
        go version
        kustomize version
        helm version
        kubebuilder version
        kind version
    - name: Create kind cluster
      uses: helm/kind-action@v1.13.0
      with:
        version: v0.27.0
        node_image: kindest/node:${{ matrix.kindest_node_version }}
        kubectl_version: v1.32.2
        # config: test-resources/kind-config.yaml
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build
      uses: docker/build-push-action@v6
      with:
        context: .
        load: true
        tags: amazeeio/dbaas-operator:test-tag
    - name: Run Tests
      run: |
        make operator-test
