name: DBaaS Operator Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"
    - name: Set up testing dependencies
      run: sudo apt-get update && sudo apt-get -y install build-essential && sudo apt-get clean
    - name: Install go, kustomize, kubebuilder, helm, docker-compose, kind
      run: |
        #go
        sudo rm -rf /usr/local/go
        curl -sLo /tmp/go1.13.7.linux-amd64.tar.gz https://dl.google.com/go/go1.13.7.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf /tmp/go1.13.7.linux-amd64.tar.gz
        #kustomize
        curl -sLo /tmp/kustomize_v3.5.4_linux_amd64.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.5.4/kustomize_v3.5.4_linux_amd64.tar.gz
        sudo tar -C /usr/local/bin -xzf /tmp/kustomize_v3.5.4_linux_amd64.tar.gz
        #kubebuilder
        curl -sL https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.2.0/kubebuilder_2.2.0_linux_amd64.tar.gz | tar -xz -C /tmp/
        sudo mv /tmp/kubebuilder_2.2.0_linux_amd64 /usr/local/kubebuilder
        #helm
        curl -sL https://get.helm.sh/helm-v3.3.0-rc.1-linux-amd64.tar.gz | tar -xz -C /tmp/
        sudo mv /tmp/linux-amd64/helm /usr/local/bin/helm
        chmod +x /usr/local/bin/helm
        #docker-compose
        sudo curl -sLo /usr/local/bin/docker-compose "https://github.com/docker/compose/releases/download/1.29.0/docker-compose-$(uname -s)-$(uname -m)"
        sudo chmod +x /usr/local/bin/docker-compose
        #kind
        curl -sLo /tmp/kind https://github.com/kubernetes-sigs/kind/releases/download/v0.11.1/kind-linux-amd64
        chmod +x /tmp/kind
        sudo mv /tmp/kind /usr/local/bin/
    - name: Create kind cluster
      uses: helm/kind-action@v1.1.0
      # with:
      #   config: test-resources/kind-config.yaml
    - name: Run Tests
      run: |
        export PATH=$PATH:/usr/local/kubebuilder/bin
        export PATH=$PATH:/usr/local/go/bin
        export GOPATH=$HOME/go
        # export GO111MODULE=on
        make operator-test